namespace NAP.Core;

/// <summary>Frozen expected production content; generated bytes are copied on input and output.</summary>
public sealed class ProductionAssetFile
{
    private readonly byte[]? _generated;

    internal ProductionAssetFile(ProductionAssetFileKind kind, string role, string fileName, string? sourcePath,
        string destinationPath, Sha256Digest digest, long sizeBytes, byte[]? generated)
    {
        ArgumentNullException.ThrowIfNull(digest);
        ArgumentException.ThrowIfNullOrWhiteSpace(role);
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationPath);
        if (!Enum.IsDefined(kind) || !ProductionPaths.SafeSegment(fileName) || sizeBytes < 0 ||
            (kind == ProductionAssetFileKind.GeneratedWebp ? generated is null || sourcePath is not null : generated is not null || string.IsNullOrWhiteSpace(sourcePath)))
            throw new ArgumentException("Expected coherent frozen production file content.");
        if (generated is not null)
        {
            using var input = new MemoryStream(generated, writable: false);
            if (generated.LongLength != sizeBytes || new Sha256Hasher().Compute(input) != digest)
                throw new ArgumentException("Generated bytes must match the expected SHA and size.", nameof(generated));
        }
        Kind = kind; Role = role; FileName = fileName; SourcePath = sourcePath; DestinationPath = destinationPath;
        Digest = digest; SizeBytes = sizeBytes; _generated = generated is null ? null : (byte[])generated.Clone();
    }

    public ProductionAssetFileKind Kind { get; }
    public string Role { get; }
    public string FileName { get; }
    public string? SourcePath { get; }
    public string DestinationPath { get; }
    public Sha256Digest Digest { get; }
    public long SizeBytes { get; }
    public byte[] ToArray() => _generated is null ? throw new InvalidOperationException("Only generated WebP files contain in-memory bytes.") : (byte[])_generated.Clone();
    internal void WriteGenerated(Stream output) => output.Write(_generated ?? throw new InvalidOperationException("Expected generated output."));
}
